# Themes Setting #
currentTheme = archcraft
background = /usr/share/backgrounds/i3default.png
theme = Tokyonight-Dark-B
icons = Elena-dark-icons
cursor = WineTrix
polybar = archcraft
change-betterlockscreen = false

# i3 Configurations, Appearance and Other Setting #
picom = default.conf
multi-bar-monitors = true
keyboard-layouts = us


# secret keys #
github-username = 
github-access-token = 
weather-API = 
weather-city-ID = 

