preload = /home/ivan/Pictures/wallpapers/ichigo_final_getsuga_tensho.jpg

# Try using the description for HDMI-A-1
wallpaper{
		monitor= HDMI-A-1
		path = /home/ivan/Pictures/wallpapers/ichigo_final_getsuga_tensho.jpg
		fit_mode = cover
	}
wallpaper{
		monitor = DVI-I-1
		path = /home/ivan/Pictures/wallpapers/ichigo_final_getsuga_tensho.jpg
		fit_mode= cover
		}	

splash = false
